### ISSUE TITLE
Python error when params values used in pylintrc

### ISSUE THREAD

**Issue by kbalk** [sebdah/git-pylint-commit-hook#47]
I created a .pylintrc as follows:

```
[pre-commit-hook]
params="--reports=n"
```

which gave me the following error:

```
Traceback (most recent call last):
  File "/home/kbalk/.virtualenvs/myenv/bin/git-pylint-commit-hook", line 69 in <module>
     main()
  File "/home/kbalk/.virtualenvs/myenv/bin/git-pylint-commit-hook", line 62 in main
     args.limit, args.pylint, args.pylintrc, args.pylint_params, args.suppress_report)
  File "/home/kbalk/.virtualenvs/myenv/local/lib/python2.7/site-packages/git_pylint_commit_hook/commit_hook.py", line 177, in check_repo
    pylint_params += '' + conf.get('pre-commit-hook', 'params')
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

pylint_params has a default value of None and the value in the config file is a string; a possible solution in commit_hook.py:

```
new_params = confg.get('pre-commit-hook', 'params')
if pylint_params:
    pylint_params += ' ' + new_params
else:
    pylint_params = new_params
```

**Comment by jakehilton** [comment]
A workaround for now.. is to change your pre-commit script to look like this:
```
#!/usr/bin/env bash
git-pylint-commit-hook --pylint-params=''
```
So you give pylink_params a default value of an empty string. That will at least allow you to put your params in your .pylintrc file instead of in the pre-commit.
