### ISSUE TITLE
Cannot use git-pylint-commit-hook with the pre-commit.com hook

### ISSUE THREAD

**Issue by aleb** [sebdah/git-pylint-commit-hook#59]
I'm using the pre-commit.com git hook and in `.git/hooks/pre-commit.legacy` (which is called by the pre-commit.com hook) I call `git-pylint-commit-hook`:
```
$ cat .git/hooks/pre-commit.legacy
#!/usr/bin/env bash
python3 /app/bin/git-pylint-commit-hook --pylintrc=/home/aleb/dev/ptv-stable/pitivi/docs/pylint.rc --limit=10.0 --suppress-report || exit 1
```

I get an error when I try to commit something, saying `index.lock` exists already:
```
Running in sandbox: python3 /app/bin/git-pylint-commit-hook --pylintrc=/home/aleb/dev/ptv-stable/pitivi/docs/pylint.rc --ignore=bin/pitivi.in --limit=10.0 --suppress-report
fatal: Unable to create '/home/aleb/dev/ptv-stable/pitivi/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Cannot save the current index state
Traceback (most recent call last):
  File "/app/bin/git-pylint-commit-hook", line 83, in <module>
    result = main()
  File "/app/bin/git-pylint-commit-hook", line 80, in main
    args.ignored_files)
  File "/app/lib/python3.5/site-packages/git_pylint_commit_hook/commit_hook.py", line 206, in check_repo
    with _stash_unstaged():
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/app/lib/python3.5/site-packages/git_pylint_commit_hook/commit_hook.py", line 137, in _stash_unstaged
    subprocess.check_call('git stash save -q --keep-index '
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'stash', 'save', '-q', '--keep-index', 'git-pylint-commit-hook']' returned non-zero exit status 1
```

```
Running in sandbox: python3 /app/bin/git-pylint-commit-hook --version
git-pylint-commit-hook version 2.2.2
```

Any idea how I can make git-pylint-commit-hook work with pre-commit.com? I should find out what exactly creates that file.

**Comment by aleb** [comment]
Because of the way we have our dev env set up, there is a different git version in it than the system one. That's why running "git stash" while "git commit"-ing does not work, because they are run by different git binaries, or so it seems.
