### ISSUE TITLE
failure to commit binary file

### ISSUE THREAD

**Issue by asheeshrana** [sebdah/git-pylint-commit-hook#67]
My repository has binary files that needs to be checked in.
git-pylint-commit-hook fails to identify the file as a non python file causing the commit to fail. I get the following exception.

~~~
Running pylint git hook
Traceback (most recent call last):
  File "/usr/local/bin/git-pylint-commit-hook", line 90, in <module>
    result = main()
  File "/usr/local/bin/git-pylint-commit-hook", line 87, in main
    args.stash)
  File "/usr/local/lib/python3.6/site-packages/git_pylint_commit_hook/commit_hook.py", line 226, in check_repo
    if _is_python_file(filename) and \
  File "/usr/local/lib/python3.6/site-packages/git_pylint_commit_hook/commit_hook.py", line 79, in _is_python_file
    first_line = file_handle.readline()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 0: invalid continuation byte
~~~

Adding ignore option doesn't seem to help as well. It seems ignore option supplied directly to the git-pylint-commit-hook or even via .pylintrc are evaluated "after" the tool evaluates "_is_python_file(filename)".

Suggest to evaluate any "ignore" parameter supplied first and if a file is already in ignore list then no need to check if it is even a python file.

**Comment by mitjanikolaus** [comment]
Same issue here when trying to commit a zip file.

**Comment by kush-jain** [comment]
I am facing the same issue, and could potentially help out on same.

Some of the potential fixes from the top of my head:
1. in `_is_python_file` wrap Read op in try/except block, and if it fails, return False
2. Read the file in binary format, and tweak the conditions accordingly.

If there is a clear consensus on best way forward, I can tackle this quickly

**Comment by yibinlin** [comment]
> I am facing the same issue, and could potentially help out on same.
> 
> Some of the potential fixes from the top of my head:
> 
> 1. in `_is_python_file` wrap Read op in try/except block, and if it fails, return False
> 2. Read the file in binary format, and tweak the conditions accordingly.
> 
> If there is a clear consensus on best way forward, I can tackle this quickly

I think that is the error I got too.

**Comment by stapetro** [comment]
I hit the same issue with *.png images. I worked around the problem using _--ignore_ CLI parameter.

**Comment by sashwin-vunet** [comment]
I'm facing the same issue when trying to commit `*.png` files. 
Is there any update on this issue, can we validate and merge the above PR
